name = "SmoQyKPMCore"
uuid = "30e33e58-a96a-4fec-8c75-57692dd3ff18"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>", "Steven Johnston <sjohn145@utk.edu>", "Kipton Barros <kbarros@lanl.gov>"]
version = "0.1.5"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
SmoQyKPMCoreCUDA = "CUDA"

[compat]
Adapt = "4.1.1"
CUDA = "5.5"
FFTW = "1.8"
LinearAlgebra = "1.10"
Random = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
